# This is a basic workflow to help you get started with Actions
name: Job status
on:
  push:
jobs:
    information_display:
        name: information display
        runs-on: ubuntu-latest
        steps:
        - run: | 
            echo "::notice:: Ceci est une notice."
            echo "::warning:: Ceci est un avertissement."
            echo "::error:: Une erreur est survenue."
    log_group:
        runs-on: ubuntu-latest
        steps:
        - run: | 
            echo "::group:: ecoleit"
            echo "hello, ecole-it."
            echo "::endgroup::"
            echo "Ceci n'est pas dans le groupe"
    prepare_tests:
      runs-on: ubuntu-latest
      outputs:
        HOST: ${{steps.setupdb.outputs.HOST}}
        DATABASE: ${{steps.setupdb.outputs.DATABASE}}
      steps:
        - name: "Setup db"
          id: setupdb
          run: | 
            echo "HOST=srv1 >> $GITHUB_OUTPUT"
            echo "DATABASE=prep002 >> $GITHUB_OUTPUT"
              
    display_infos:
      needs: prepare_tests
      runs-on: ubuntu-latest
      steps:
        - name: "Display variables"
          run: |
              echo "HOST= ${{needs.prepare_tests.outputs.HOST}}"
              echo "DATABASE= ${{needs.prepare_tests.outputs.DATABASE}}"
        