# This is a basic workflow to help you get started with Actions

name: say_hello
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      username:
        default: Dim
        type: string
      level:
        type: string
      class: 
        type: choice
        options:
        - jedi
        - sith
        - rebel
jobs:
  player_infos:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Le joueur ${{inputs.username}} est de niveau ${{inputs.level}} et joue un ${{inputs.class}}"